# Generated by Django 2.2.6 on 2019-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.CharField(default=2, max_length=8),
            preserve_default=False,
        ),
    ]
